#!/usr/bin/env bash

#### MONITORS ####
bspc monitor -d 1 2 3 4 5 6 7 8

external_monitor=$(xrandr --query | grep 'VGA-1')

if [[ $external_monitor = VGA-1\ connected* ]]; then
    xrandr --output VGA-1 --primary --auto --output LVDS-1 --auto --right-of VGA-1
	bspc monitor VGA-1 -d 1 2 3 4
	bspc monitor LVDS-1 -d 5 6 7 8 
else
	xrandr --output LVDS-1 --auto
	bspc monitor LVDS-1 -d 1 2 3 4 5 6 7 8 
fi

# Truncate a couple of common commands that are used herein.
_bc() {
	bspc config "$@"
}


#### BSPWM configuration ####
_bc window_gap 			              5
_bc top_padding 		              26
_bc top_monocle_padding 	        0
_bc border_width 		              2
_bc bottom_padding                0
_bc left_padding                  0
_bc right_padding 		            0
_bc single_monocle                false
_bc click_to_focus                false
_bc split_ratio                   0.50
_bc borderless_monocle            true
_bc gapless_monocle               true
_bc focus_by_distance             true
_bc paddingless_monocle  	        true
_bc focus_follows_pointer         true
_bc ignore_ewmh_focus 		        true
_bc history_aware_focus           true
_bc remove_disabled_monitors      true
_bc merge_overlapping_monitors    true
_bc pointer_follows_monitor 	    true
_bc pointer_modifier mod1
_bc pointer_action1 move
_bc pointer_action2 resize_side
_bc pointer_action3 resize_corner

# Colors
bspc config active_border_color "#474f54"
bspc config focused_border_color "#474f54"
bspc config normal_border_color "#373d41"
bspc config presel_feedback_color "#373d41"

# Rules
bspc rule -a whatsdesk desktop="^3"
bspc rule -a whatsdesk state=floating
bspc desktop -f 1

# Autostart
~/.config/bspwm/autostart &
