[colors.bright]
black = "#6b7089"
blue = "#91acd1"
cyan = "#95c4ce"
green = "#c0ca8e"
magenta = "#ada0d3"
red = "#e98989"
white = "#d2d4de"
yellow = "#e9b189"

[colors.hints.end]
background = "#4C566A"
foreground = "#81A1C1"

[colors.hints.start]
background = "#4C566A"
foreground = "#B988B0"

[colors.normal]
black = "#161821"
blue = "#84a0c6"
cyan = "#89b8c2"
green = "#b4be82"
magenta = "#a093c7"
red = "#e27878"
white = "#c6c8d1"
yellow = "#e2a478"

[colors.primary]
background = "#1b1918"
foreground = "#d2d4de"

[colors.search.focused_match]
background = "#4C566A"
foreground = "#EBCB8B"

[colors.search.matches]
background = "#4C566A"
foreground = "#81A1C1"

[colors.selection]
background = "#3F4758"
text = "CellForeground"

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0

[window]
opacity = 0.88

[window.padding]
x = 10
y = 10
