#!/usr/bin/env bash
#exec w3m "duckduckgo.com/lite?kd=-1&kp=-1&q=$*"
exec ~/.scripts/lynx "https://lite.duckduckgo.com/lite?kd=-1&kp=-1&q=$*" # 🦆
#exec lynx "duckduckgo.com/lite?q=$*" # 🦆
#exec lynx "duckduckgo.com/lite?q=$*"
