#!/usr/bin/env bash

cleanup() {
	lf-ueberzug-cleaner
	kill "$UEBERZUGPID"
	pkill -f "tail -f $LF_UEBERZUG_TEMPDIR/fifo"
	rm -rf "$LF_UEBERZUG_TEMPDIR"
  rm -rf "$LF_SCROLLINGPREVIEW_TEMPDIR"
}
trap cleanup INT HUP TERM

# Set up temporary directory.
export LF_UEBERZUG_TEMPDIR="$(mktemp -d -t lf-ueberzug-XXXXXX)"
export LF_SCROLLINGPREVIEW_TEMPDIR="$(mktemp -d -t lf-scrollingpreview-XXXXXX)"

# Initialize scrolling offset (page number or line offset)
echo "1" >"$LF_SCROLLINGPREVIEW_TEMPDIR/offset"

# Launch ueberzug.
mkfifo "$LF_UEBERZUG_TEMPDIR/fifo"
tail -f "$LF_UEBERZUG_TEMPDIR/fifo" | ueberzug layer --silent &
UEBERZUGPID=$!

# Add this script's directory to PATH so that the lf config will find
# lf-ueberzug-cleaner and lf-ueberzgu-previewer. If no startup directory is
# provided, start lf in the examples directory.
lf -config ~/.config/lf/lfrc
cleanup
