#!/usr/bin/env bash

fname=`ncmpcpp --quiet --current-song "%f"`
file=`find ~/Music -name "$fname"`

ffmpeg -i "$file" -loglevel quiet  -an -vcodec copy -y /tmp/cover.jpg
if [ -e /tmp/cover.jpg ]
then
	notify-send "Now Playing" "$(mpc --format '%title% \n%artist% - %album%' current)"\
		-i /tmp/cover.jpg \
		-h string:synchronous:nowplaying
	rm /tmp/cover.jpg
else
	notify-send "Now Playing" "$(mpc --format '%title% \n%artist% - %album%' current)" \
		 -i ~/player_icon.png \
		-h string:synchronous:nowplaying
fi
